### PR TITLE
Added in Coronavirus Disease ressources

### PR DESCRIPTION
**Pull request by aminblm**

### CODE REVIEW

**Comment by javieraviles** [comment]
i don't really get this?

**Comment by m3talux** [comment]
Looks like someone is trying to advertise his repo maybe.

**Comment by javieraviles** [comment]
I think he is just "Building stuff for fun", so let's understand it was just a wrong click :)

**Comment by asksouley** [comment]
Hey  guys

 I just subscribed to your repos. Not sure if the thread here is about me
or not .
Sincerely
Souleymane Tiendrebeogo

**Pull request closed without merging**
