### PR TITLE
Additional Data to Global results

### PR DESCRIPTION
**Pull request by dewald-els**
Added Additional Data to Global info
result.currentlyInfected: { count, mildInfection, serious };
result.closedCases : { count, recovered, deaths }

### CODE REVIEW

**Comment by javieraviles** [comment]
I like most of the changes here, but why removing the frontend?

**Comment by javieraviles** [comment]
I mean I'm fine with the changes, they improve everything in general as I did not spent much time here, but i would like to keep the frontend as this contains a pipeline deploying to Heroku and is receiving 20-50 req/second

**Comment by dewald-els** [comment]
oh crap! Sorry! that was for my fork!  my bad. I was building a Ionic app as well and didn't want to mess with yours!

**Comment by dewald-els** [comment]
I totally forgot that My commits would pull through ti the pull request.

**Pull request closed without merging**
