### PR TITLE
Tests per million

### PR DESCRIPTION
**Pull request by joelbduncan**
Fixed mistake in last pull request, now tested working.

Adds two new columns to API:

Total Tests
Tests per one million population

### CODE REVIEW

**Comment by joelbduncan** [comment]
Sorry for the extra commits, I'm using a fork of this where I've replaced spaces in names with underscores so it plays nicely with PHP. Rushed it a bit!

**Comment by mncfre** [comment]
The countries api it’s not working

**Comment by joelbduncan** [comment]
> The countries api it’s not working

Using this PR or master branch from developer? This PR should fix the countries endpoint.

**Comment by Blackmore23** [comment]
No Data by using:

https://coronavirus-19-api.herokuapp.com/countries

**Comment by MaciejHeintze** [comment]
API stopped working around 1 hour ago let us know what's going on @javieraviles

**Comment by kostodo** [comment]
API is down...

**Comment by MaciejHeintze** [comment]
why?

**Comment by javieraviles** [comment]
countries endpoint is not working because worldometers just added tests column, let me merge this PR and github actions will deploy to heroku in 3 minutes :)

**Comment by kostodo** [comment]
Was just confirming it's down. I have no idea. Here to find out more just like you

**Comment by javieraviles** [comment]
By the way @Slethen  thank you very much for the PR!!!

**Review by javieraviles — APPROVED** [review]

**Comment by MaciejHeintze** [comment]
@javieraviles thanks :) take care

**Comment by javieraviles** [comment]
Okay its merged so this pipeline

https://github.com/javieraviles/covidAPI/actions/runs/70645736

is deploying right now, give it 3-4 min and the api should be up there including tests information :)

Sorry for the inconvenience!!

**Comment by joelbduncan** [comment]
> By the way @Slethen thank you very much for the PR!!!

No problem at all!

I do wonder if there's a way to count the columns to prevent downtime when they're added.
If I get a chance I'll look at it :) I personally use original project's API as a backup to my fork when UK cases are higher on there API.

Thanks!

**Comment by javieraviles** [comment]
surely there is, might be worth spend some time on that, sounds quite doable :)

**Comment by joelbduncan** [comment]
> surely there is, might be worth spend some time on that, sounds quite doable :)

I think I've done it, PR coming. Make sure it's sane before you merge.

**Pull request merged**
